### ISSUE TITLE
Husks & Carrions Not Spawning

### ISSUE THREAD

**Issue by theplayerthatexists** [swc132994/BD64-VoH_game#10]
For some reason, no matter how many times I change the settings, the husks won't spawn in game. I have tried to change the monster spawning options to every option possible to see if one of them might work. Long story short, no matter what I do, husks & carrions will not spawn in game. And yes, I have pressed Apply every time I change the setting.

**Comment by swc132994** [comment]
Make sure you download the latest version. There is now only 1 setting in the monster spawning options. Remember, these guys only spawn around dead zombie/marine props placed on the maps (if maps don't have dead props then they cannot spawn)

Carrions spawn only with the x3 and x4 husk setting.

**Comment by theplayerthatexists** [comment]
Yes, I know that they spawn around dead marine props. I tested the issue with maps that have dead marine props such as HontE Remastered Map 30 & your Doom 64 maps. I just downloaded the latest version yesterday and it still does not work.

**Comment by swc132994** [comment]
It's definitely working for me.From: theplayerthatexists ***@***.***>Sent: Friday, June 28, 2024 1:03:35 pmTo: swc132994/BD64game_v2.666 ***@***.***>Cc: Steven Connell ***@***.***>; Comment ***@***.***>Subject: Re: [swc132994/BD64game_v2.666] Husks & Carrions Not Spawning (Issue #10)
Yes, I know that they spawn around dead marine props. I tested the issue with maps that have dead marine props such as HontE Remastered Map 30 & your Doom 64 maps. I just downloaded the latest version yesterday and it still does not work.

**Comment by swc132994** [comment]
It's definitely working for me.
Are you using any add-on that replaces props?
What are your add-ons?

**Comment by theplayerthatexists** [comment]
![image](https://github.com/swc132994/BD64game_v2.666/assets/148651085/4be247c1-9b57-4afc-a2ba-ecdb74eaeb73)
These are my addons.

**Comment by theplayerthatexists** [comment]
FYI, ADAMP is a music replacement mod.

**Comment by theplayerthatexists** [comment]
> It's definitely working for me. Are you using any add-on that replaces props? What are your add-ons?

The issue could be the D64 texture mods since I've switched to the latest version from Moddb

**Comment by theplayerthatexists** [comment]
> > It's definitely working for me. Are you using any add-on that replaces props? What are your add-ons?
> 
> The issue could be the D64 texture mods since I've switched to the latest version from Moddb

Just tested BD64 game with vanilla doom 2 maps using only the BD64 game file, the husks are still not appearing. One thing I recall is that the husks used to spawn for me on previous versions of the BD64 game until I switched to the latest update.

**Comment by swc132994** [comment]
Remove the props beta add-on. It replaces props which is a no no.

**Comment by theplayerthatexists** [comment]
It works now, thx for the help!
