### ISSUE TITLE
Suggestion - Make the acid demon to inflict direct damage when attacked with a chainsaw.

### ISSUE THREAD

**Issue by VerianCS** [swc132994/BD64-VoH_game#13]

**Comment by BigStronk64** [comment]
Could you explain?

**Comment by VerianCS** [comment]
When you attack an acid demon with a chainsaw it could be good if it cause acid damage.

**Comment by swc132994** [comment]
I have an idea how to add this. It should be added soon.

**Comment by swc132994** [comment]
Check out the latest upload. When the acid demon is in its pain state, it will spawn acid blood.

**Comment by VerianCS** [comment]
Excellent!

**Comment by swc132994** [comment]
Acid monsters now bleed acid on pain.
