### ISSUE TITLE
ZMovement addon causes security cameras to not work

### ISSUE THREAD

**Issue by gsanjin** [swc132994/BD64-VoH_game#16]
First, thank you for continued work on BD64 and everyday improvement!

I noticed when using https://drive.google.com/file/d/1u4P-zICwz9zkCKXCUj6nbhq91i2AOd7k (ZMovement addon for BD64), security cameras are not working. Screen just flashes for a moment when trying to view cameras.

If I disable/skip loading ZMovement addon, all is working ok, but without ZMovement ... Any chance to check this issue? I am using latest stable GZDoom 4.12.2 and batch files for loading (no drag'n'drop).

**Comment by swc132994** [comment]
I have contacted the addon creator. At the moment, he doesn't have any ideas.

BTW, GZDoom 4.12.2 has a bug with monsters being able to lookallaround so you can never sneak up on monsters. I suggest using the dev version of GZDoom as this has been resolved there.

https://devbuilds.drdteam.org/gzdoom/

**Comment by gsanjin** [comment]
Thank you swc132994 for detail/recommendation! Just for case, I checked this with latest GZDoom build and same sec. camera issue is present. Since you're not author of BD64 ZMovement addon mod, I will close this.
